---
    name: Terraform Validate
    on:
      pull_request:
       types: [opened, edited]
       paths:
        - '**.tf'
      push:
        branches:
         - testing
         - main
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json
    
    jobs:
      trivy-test:
        name: tf-validate
        runs-on: ubuntu-latest
        # These permissions are needed to interact with GitHub’s OIDC Token endpoint.
        permissions:
          id-token: write
          contents: read
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-region: us-east-1
            ## the following creates an ARN based on the values entered into github secrets
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            role-session-name: TrivyCheckSession
        - uses: hashicorp/setup-terraform@v3

        - name: Terraform Init
          run: terraform init
          working-directory: ./src/dev

        - name: Terraform Validate
          run: terraform validate -no-color
          working-directory: ./src/dev

        - name: Terraform Format
          run: terraform fmt -diff -recursive
